/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RadButton {
        "color": "primary" | "secondary" | "transparent" | "success";
        "disabled": boolean;
        "fullWidth": boolean;
        "loading": boolean;
        "shadow": boolean;
        "size": "medium" | "small";
        "type": string;
        "width": number;
    }
    interface RadInput {
        "disabled": boolean;
    }
    interface RadLoadingDots {
    }
}
declare global {
    interface HTMLRadButtonElement extends Components.RadButton, HTMLStencilElement {
    }
    var HTMLRadButtonElement: {
        prototype: HTMLRadButtonElement;
        new (): HTMLRadButtonElement;
    };
    interface HTMLRadInputElement extends Components.RadInput, HTMLStencilElement {
    }
    var HTMLRadInputElement: {
        prototype: HTMLRadInputElement;
        new (): HTMLRadInputElement;
    };
    interface HTMLRadLoadingDotsElement extends Components.RadLoadingDots, HTMLStencilElement {
    }
    var HTMLRadLoadingDotsElement: {
        prototype: HTMLRadLoadingDotsElement;
        new (): HTMLRadLoadingDotsElement;
    };
    interface HTMLElementTagNameMap {
        "rad-button": HTMLRadButtonElement;
        "rad-input": HTMLRadInputElement;
        "rad-loading-dots": HTMLRadLoadingDotsElement;
    }
}
declare namespace LocalJSX {
    interface RadButton {
        "color"?: "primary" | "secondary" | "transparent" | "success";
        "disabled"?: boolean;
        "fullWidth"?: boolean;
        "loading"?: boolean;
        "shadow"?: boolean;
        "size"?: "medium" | "small";
        "type"?: string;
        "width"?: number;
    }
    interface RadInput {
        "disabled"?: boolean;
    }
    interface RadLoadingDots {
    }
    interface IntrinsicElements {
        "rad-button": RadButton;
        "rad-input": RadInput;
        "rad-loading-dots": RadLoadingDots;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rad-button": LocalJSX.RadButton & JSXBase.HTMLAttributes<HTMLRadButtonElement>;
            "rad-input": LocalJSX.RadInput & JSXBase.HTMLAttributes<HTMLRadInputElement>;
            "rad-loading-dots": LocalJSX.RadLoadingDots & JSXBase.HTMLAttributes<HTMLRadLoadingDotsElement>;
        }
    }
}
